### ISSUE TITLE
Like

### ISSUE THREAD

**Issue by Jakob1357** [furongkingdevops/products#15]
**As a** user  
 **I need** to know how many people like this product
 **So that** I could obtain more product-related information
   
 ### Details and Assumptions
 * Use a variable to store the number of likes 
 * If a user likes a product, he/she/it can choose to click like and increase the like variable by 1
 * If a user liked a product, he/she/it can cancel the like and decrease the like variable by 1
 * A user cannot dislike a product if he/she/it did not liked it before
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the information a user likes the product or not
 When the user click the like button
 Then increase or decrease the like variable by 1
 ```

**Comment by ElioZhou** [comment]
This should be an action for the product API to be able to like or dislike a product.
